# Generated by Django 6.0.2 on 2026-03-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playercard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='duplicate_count',
            field=models.IntegerField(default=0),
        ),
    ]
